---
title: "negbin_glm"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{negbin_glm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#require(MASS)
library(adaglm)
```

Simulate data under NB GLM. 
```{r}
N = 1000
P = 10
X = matrix(rnorm(N*P), N, P)
true_conc = 5. 
true_b = rnorm(P)
offs = rnorm(N)
y = MASS::rnegbin(N, mu = exp(X %*% true_b + offs), theta = true_conc)
df = as.data.frame(X)
df$y = y
df$offs = offs
head(df)
```
Fit to obtain `glm` object. 
```{r}
my_nb_fit = adaglm(y ~ . - offs + offset(offs), data = df, verbose = F, loglik_tol = 0.1)
plot(c(0, true_b), my_nb_fit$coefficients, ylab = "Estimated coefficients", xlab = "True coefficients")
```

How well did we estimate the concentration (1/dispersion) parameter? 

```{r}
my_nb_fit$theta # true is 5. 
```

Summary gives statistical significance for each covariate
```{r}
summary(my_nb_fit) # just "summary" should work here but gets 
```

Use a likelihood ratio test to determine significance of one covariate (V1). 
```{r}
my_nb_fit_null = adaglm(y ~ . - offs + offset(offs) - V1, data = df, verbose = F, loglik_tol = 0.1)
summary(my_nb_fit_null)
```

```{r}
anova(my_nb_fit,my_nb_fit_null)
```
